language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Kj34ePmdMrhEkSMMXUrVd1tX/0l9OnAze3cNAjeyKuFn3mSdM9DcXy7TstJb023tJQ57PIX+LDFyZCGe8vubwSfFeULZLBIyaSsaZw6wfZTkobla99f3oWm+1iGhUU7aLbH+31U4k6aEUsU2S/VtPo/TbrW6/P8wzGiWIC2j1OObnZqiB2a0UUlqEGEqsMwv/9tI/EMkx/qYN2/MJJUj1KYORMQcZCI8cv6R2XnSSZ7lHeuOsN67hB/WotZyfrihsFRY0ANT4J94ateiX2E9BFBLFtjQwa8T2JsFh8Q+Ex7otgQIegu+Jum9x8/EAUGtiopgz4PCeWCey2Ri0mywKLIl+ewQvAlX0zNjreBKNpumcPd4UKXCLQHTpPjbNjNzgGyVBT161xipx1PrCgAKlSX2PS3dydLArwOlYnE+EK8xbBCHonLsnyHrm4xSJKZk1ypeNMEd7jaxBbkFlHkvcWselIA6Y4xSjxb9szY8QlDU5oKuNzOtVZrOxHY9IXijP3aub889D4yzbtNc1oBhDFpdiPLbHO0KAo6bOzR4/kDLjm0KEOYHcmZqMDSX+YKwfOOfJEVGKTjekpi1FBoN9in6Y3piJgpkvURjp6tDMYaC9C2dBFGbhKNPNQDLSoMvfBzdemAk8AJjx6tTT9ZdmWCNcP+XjGG2vuNDZEz7sq4=
  file:
    - "hastscript.js"
    - "hastscript.min.js"
  on:
    tags: true
